# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: dnf5.spec

# add or remove files that should be synced
files_to_sync:
  - dnf5.spec
  - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: dnf5
# downstream (Fedora) RPM package name
downstream_package_name: dnf5

jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
      - fedora-39
      - fedora-38
    copy_upstream_release_description: true
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
      - fedora-39
      - fedora-38
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-39
      - fedora-38 # rawhide updates are created automatically
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    fmf_url: https://github.com/rpm-software-management/ci-dnf-stack.git
    fmf_ref: main
    tmt_plan: /plans/integration/behave-dnf5
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
    fmf_url: https://github.com/rpm-software-management/ci-dnf-stack.git
    fmf_ref: main
    tmt_plan: /plans/integration/behave-createrepo_c
  - job: tests
    trigger: pull_request
    manual_trigger: true
    targets:
      - fedora-all
    fmf_url: https://github.com/rpm-software-management/ci-dnf-stack.git
    fmf_ref: main
    tmt_plan: /plans/integration/behave-dnf
  - job: tests
    trigger: pull_request
    manual_trigger: true
    targets:
      - fedora-all
    fmf_url: https://github.com/rpm-software-management/ci-dnf-stack.git
    fmf_ref: main
    tmt_plan: /plans/integration/behave-dnf5daemon
