files_to_sync:
  - dnf5.spec

jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
        - fedora-rawhide
        - fedora-38
  - job: koji_build
    trigger: commit
    dist_git_branches:
        - fedora-rawhide
        - fedora-38
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
        - fedora-38 # rawhide updates are created automatically
