# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: dnf5.spec

# add or remove files that should be synced
files_to_sync:
  - dnf5.spec
  - .packit.yaml

actions:
  fix-spec-file:
    # set the correct version for global project_version_{major,minor,patch} macros needed by %build
    bash -c "sed -i -r \"s/^%global project_version_major (\s*)\S+/%global project_version_major \1`echo ${PACKIT_PROJECT_VERSION} | cut -d. -f1`/\" dnf5.spec"
    bash -c "sed -i -r \"s/^%global project_version_minor (\s*)\S+/%global project_version_minor \1`echo ${PACKIT_PROJECT_VERSION} | cut -d. -f2`/\" dnf5.spec"
    bash -c "sed -i -r \"s/^%global project_version_patch (\s*)\S+/%global project_version_patch \1`echo ${PACKIT_PROJECT_VERSION} | cut -d. -f3`/\" dnf5.spec"

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: dnf5
# downstream (Fedora) RPM package name
downstream_package_name: dnf5

jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
      - fedora-38
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
      - fedora-38
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-38 # rawhide updates are created automatically
