version: 2

build:
  os: "ubuntu-lts-latest"
  apt_packages:
    - swig
    - cmake
    - doxygen
  tools:
    python: latest
  jobs:
    build:
      html:
        - pip install -r doc/requirements.txt
        - |
          cmake -B build -S . \
          -DWITH_TESTS=OFF \
          -DWITH_RUBY=OFF \
          -DWITH_PERL5=OFF \
          -DWITH_GO=OFF \
          -DWITH_PYTHON3=ON \
          -DENABLE_HTML_ONLY=ON
        - cmake --build build --target doc-html
        - mkdir -p $READTHEDOCS_OUTPUT/
        - cp -r build/doc/html $READTHEDOCS_OUTPUT/
