#!/bin/sh


# run clang-format on new and modified files
# apply the changes immediately


TOPDIR=$(dirname $(readlink -f $0))


# get upstream branch (incl. remote)
UPSTREAM_BRANCH=`git rev-parse --abbrev-ref --symbolic-full-name @{u}`

# list all changed files
CHANGED_FILES=`git diff --name-only "$UPSTREAM_BRANCH" | egrep '\.(c|cpp|h|hpp)$'`

# list all untracked files
UNTRACKED_FILES=`git ls-files --others --exclude-standard | egrep '\.(c|cpp|h|hpp)$'`


for FILE in $CHANGED_FILES $UNTRACKED_FILES; do
    echo "Formatting $FILE..."
    clang-format -i "$FILE"
done
