// Copyright Contributors to the libdnf project.
// SPDX-License-Identifier: LGPL-2.1-or-later

#ifndef LIBDNF5_LOGGER_GLOBAL_LOGGER_HPP
#define LIBDNF5_LOGGER_GLOBAL_LOGGER_HPP

#include "logger.hpp"


namespace libdnf5 {

/// GlobalLogger contains methods for setting the target (logger) for global messages - messages that are
/// generated by libraries (eg librepo) without binding to the Base object.
class LIBDNF_API GlobalLogger {
public:
    explicit GlobalLogger();
    ~GlobalLogger();

    GlobalLogger(const GlobalLogger &) = delete;
    GlobalLogger(GlobalLogger &&) = delete;
    GlobalLogger & operator=(const GlobalLogger &) = delete;
    GlobalLogger & operator=(GlobalLogger &&) = delete;

    static void set(Logger & destination, Logger::Level verbosity);
    static void unset() noexcept;
};

}  // namespace libdnf5

#endif
