# Copyright Contributors to the DNF5 project.
# SPDX-License-Identifier: GPL-2.0-or-later

use strict;
use warnings;

use Test::More;
use Test::Exception;
use File::Temp qw(tempdir);
use File::Path qw(make_path remove_tree);
use File::Spec;
use Cwd qw(abs_path);
use FindBin;

# Add path to generated test config
BEGIN {
    if ($ENV{PROJECT_BINARY_DIR}) {
        unshift @INC, "$ENV{PROJECT_BINARY_DIR}/test/perl5";
    }
}

use libdnf5::base;

# Try to load TestConfig (optional)
BEGIN {
    eval { require TestConfig; TestConfig->import(); 1 };
}

my $POLICY_COMPACT_ALLOW_CMDLINE = '@in:[cmdline_repo="1"]';

my $POLICY_TOML_ALLOW_CMDLINE = <<'EOF';
version = '1.2'

[[incoming_packages]]
filters = [
  { filter = 'cmdline_repo', value = "1" }
]
EOF

my $POLICY_COMPACT_ALLOW_FEDORA = 'in:"Fedora Project"';

my $POLICY_TOML_ALLOW_FEDORA = <<'EOF';
version = '1.2'

[[incoming_vendors]]
vendor = "Fedora Project"
EOF

my $POLICY_COMPACT_TEST_1 = 'in:ei*" test ",eq:^"MyVendor ",out:"OldVendor"';

my $POLICY_TOML_TEST_1 = <<'EOF';
version = '1.2'

[[incoming_vendors]]
vendor = " test "
comparator = 'ICONTAINS'
exclude = true

[[equivalent_vendors]]
vendor = "MyVendor "
comparator = 'STARTSWITH'

[[outgoing_vendors]]
vendor = "OldVendor"
EOF

my $POLICY_COMPACT_TEST_2 = 'in:"My Vendor"@in:[source_name="mypackage",version>="2.0"]';

my $POLICY_TOML_TEST_2 = <<'EOF';
version = '1.2'

[[incoming_vendors]]
vendor = "My Vendor"

[[incoming_packages]]
filters = [
  { filter = 'source_name', value = "mypackage" },
  { filter = 'version', value = "2.0", comparator = 'GTE' }
]
EOF


sub setup_test_base {
    my $base = new libdnf5::base::Base();
    my $temp_dir = tempdir(CLEANUP => 1, TEMPLATE => 'libdnf5_perl5_vendortest.XXXXXX');
    # Convert to absolute path
    $temp_dir = abs_path($temp_dir);

    # Set config paths (adresáře nemusí existovat před voláním set)
    $base->get_config()->get_installroot_option()->set("$temp_dir/installroot");
    $base->get_config()->get_cachedir_option()->set("$temp_dir/cache");

    # Get install prefix from test config (generated by CMake), fallback to /usr
    my $install_prefix = eval { $TestConfig::CMAKE_INSTALL_PREFIX } || "/usr";
    # Convert to relative path by removing leading /
    $install_prefix =~ s/^\///;  # Remove leading slash

    my $installroot = $base->get_config()->get_installroot_option()->get_value();

    # Create necessary directories for vendor configs
    make_path("$installroot/tmp");
    my $distrib_vendor_cfg_dir = "$installroot/$install_prefix/share/dnf5/vendors.d";
    my $system_vendor_cfg_dir = "$installroot/etc/dnf/vendors.d";
    make_path($distrib_vendor_cfg_dir);
    make_path($system_vendor_cfg_dir);

    return ($base, $distrib_vendor_cfg_dir, $system_vendor_cfg_dir);
}

sub write_file {
    my ($path, $content) = @_;
    open(my $fh, '>', $path) or die "Cannot open $path: $!";
    print $fh $content;
    close($fh);
}

sub read_file {
    my ($path) = @_;
    open(my $fh, '<', $path) or die "Cannot open $path: $!";
    local $/;
    my $content = <$fh>;
    close($fh);
    return $content;
}


# Test: load_policy_from_compact
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    $vcm->load_policy_from_compact($POLICY_COMPACT_TEST_1, "text:test");

    is($vcm->get_loaded_policies_count(), 1, "Loaded 1 policy from compact format");
    is($vcm->get_loaded_policy_source(0), "text:test", "Policy source is correct");
    is($vcm->get_loaded_policy_as_compact(0), $POLICY_COMPACT_TEST_1, "Policy as compact matches");
    is($vcm->get_loaded_policy_as_toml(0), $POLICY_TOML_TEST_1, "Policy as TOML matches");
}

# Test: load_policy_from_toml_content
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    $vcm->load_policy_from_toml($POLICY_TOML_TEST_1, "text:test");

    is($vcm->get_loaded_policies_count(), 1, "Loaded 1 policy from TOML content");
    is($vcm->get_loaded_policy_source(0), "text:test", "Policy source is correct");
    is($vcm->get_loaded_policy_as_compact(0), $POLICY_COMPACT_TEST_1, "Policy as compact matches");
    is($vcm->get_loaded_policy_as_toml(0), $POLICY_TOML_TEST_1, "Policy as TOML matches");
}

# Test: load_policy_from_toml_file
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    my $installroot = $base->get_config()->get_installroot_option()->get_value();
    my $path = "$installroot/tmp/vendor_policy.conf";

    write_file($path, $POLICY_TOML_TEST_1);

    $vcm->load_policy_from_toml($path);

    is($vcm->get_loaded_policies_count(), 1, "Loaded 1 policy from TOML file");
    my $source = $vcm->get_loaded_policy_source(0);
    is($source, "file://" . $path, "Policy source is file URI");
    is($vcm->get_loaded_policy_as_compact(0), $POLICY_COMPACT_TEST_1, "Policy as compact matches");
    is($vcm->get_loaded_policy_as_toml(0), $POLICY_TOML_TEST_1, "Policy as TOML matches");
}

# Test: convert_toml_to_compact
{
    my $compact = libdnf5::base::VendorChangeManager::convert_policy_toml_to_compact(
        $POLICY_TOML_ALLOW_CMDLINE, "text:test");
    is($compact, $POLICY_COMPACT_ALLOW_CMDLINE, "TOML to compact conversion (allow_cmdline)");

    $compact = libdnf5::base::VendorChangeManager::convert_policy_toml_to_compact(
        $POLICY_TOML_ALLOW_FEDORA, "text:test");
    is($compact, $POLICY_COMPACT_ALLOW_FEDORA, "TOML to compact conversion (allow_fedora)");

    $compact = libdnf5::base::VendorChangeManager::convert_policy_toml_to_compact(
        $POLICY_TOML_TEST_1, "text:test");
    is($compact, $POLICY_COMPACT_TEST_1, "TOML to compact conversion (test_1)");

    $compact = libdnf5::base::VendorChangeManager::convert_policy_toml_to_compact(
        $POLICY_TOML_TEST_2, "text:test");
    is($compact, $POLICY_COMPACT_TEST_2, "TOML to compact conversion (test_2)");
}

# Test: convert_toml_file_to_compact
{
    my ($base) = setup_test_base();

    my $installroot = $base->get_config()->get_installroot_option()->get_value();
    my $path = "$installroot/tmp/vendor_policy.conf";

    write_file($path, $POLICY_TOML_TEST_1);

    my $compact = libdnf5::base::VendorChangeManager::convert_policy_toml_to_compact($path);
    is($compact, $POLICY_COMPACT_TEST_1, "TOML file to compact conversion");
}

# Test: convert_compact_to_toml
{
    my $toml = libdnf5::base::VendorChangeManager::convert_policy_compact_to_toml(
        $POLICY_COMPACT_ALLOW_CMDLINE, "text:test");
    is($toml, $POLICY_TOML_ALLOW_CMDLINE, "Compact to TOML conversion (allow_cmdline)");

    $toml = libdnf5::base::VendorChangeManager::convert_policy_compact_to_toml(
        $POLICY_COMPACT_ALLOW_FEDORA, "text:test");
    is($toml, $POLICY_TOML_ALLOW_FEDORA, "Compact to TOML conversion (allow_fedora)");

    $toml = libdnf5::base::VendorChangeManager::convert_policy_compact_to_toml(
        $POLICY_COMPACT_TEST_1, "text:test");
    is($toml, $POLICY_TOML_TEST_1, "Compact to TOML conversion (test_1)");

    $toml = libdnf5::base::VendorChangeManager::convert_policy_compact_to_toml(
        $POLICY_COMPACT_TEST_2, "text:test");
    is($toml, $POLICY_TOML_TEST_2, "Compact to TOML conversion (test_2)");
}

# Test: unload_policies
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    $vcm->load_policy_from_compact('eq:"V1", in:"V2"', "text:test1");
    $vcm->load_policy_from_compact('out:"V5", eq:"V4"', "text:test2");
    is($vcm->get_loaded_policies_count(), 2, "Loaded 2 policies");

    my $unloaded_count = $vcm->unload_policies();
    is($unloaded_count, 2, "Unloaded 2 policies");
    is($vcm->get_loaded_policies_count(), 0, "All policies unloaded");
}

# Test: unload_policy
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    $vcm->load_policy_from_compact('in:"V0"', "text:source0");
    $vcm->load_policy_from_compact('in:"V1"', "text:source1");
    $vcm->load_policy_from_compact('in:"V2"', "text:source2");
    $vcm->load_policy_from_compact('in:"V3"', "text:source3");
    $vcm->load_policy_from_compact('in:"V4"', "text:source4");
    $vcm->load_policy_from_compact('in:"V5"', "text:source5");
    is($vcm->get_loaded_policies_count(), 6, "Loaded 6 policies");

    $vcm->unload_policy(2);
    is($vcm->get_loaded_policies_count(), 5, "Unloaded policy at index 2");
    is($vcm->get_loaded_policy_source(2), "text:source3", "Policy at index 2 is now source3");

    $vcm->unload_policy(4);
    is($vcm->get_loaded_policies_count(), 4, "Unloaded policy at index 4");
    is($vcm->get_loaded_policy_source(3), "text:source4", "Policy at index 3 is now source4");

    $vcm->unload_policy(0);
    is($vcm->get_loaded_policies_count(), 3, "Unloaded policy at index 0");
    is($vcm->get_loaded_policy_source(0), "text:source1", "Policy at index 0 is now source1");
    is($vcm->get_loaded_policy_source(2), "text:source4", "Policy at index 2 is now source4");

    eval { $vcm->unload_policy(999); };
    ok($@, "Unload policy with invalid index throws error");
}

# Test: unload_policies_matching_source
{
    my ($base) = setup_test_base();
    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    $vcm->load_policy_from_compact('in:"V1"', "text:source1");
    $vcm->load_policy_from_compact('in:"V2"', "text:source2");
    $vcm->load_policy_from_compact('in:"NV2"', "text:new_source2");
    $vcm->load_policy_from_compact('in:"V3"', "text:source3");
    $vcm->load_policy_from_compact('in:"V4"', "text:source4");
    $vcm->load_policy_from_compact('in:"NV3"', "text:source3");
    is($vcm->get_loaded_policies_count(), 6, "Loaded 6 policies");

    my $unloaded_count = $vcm->unload_policies_matching_source("text:source3");
    is($unloaded_count, 2, "Unloaded 2 policies matching 'text:source3'");
    is($vcm->get_loaded_policies_count(), 4, "4 policies remaining");

    $unloaded_count = $vcm->unload_policies_matching_source("te?t:*source2");
    is($unloaded_count, 2, "Unloaded 2 policies matching 'te?t:*source2'");
    is($vcm->get_loaded_policies_count(), 2, "2 policies remaining");
}

# Test: extract_policy_base_filename
{
    my $full_path = "/etc/dnf/vendors.d/my-policy.conf";
    my $base_name = libdnf5::base::VendorChangeManager::extract_policy_base_filename($full_path);
    is($base_name, "my-policy", "Extract base filename from path");
}

# Test: work_with_files
{
    my ($base, $distrib_vendor_cfg_dir, $system_vendor_cfg_dir) = setup_test_base();

    # Create TOML files
    my $distr_allow_cmdline = "$distrib_vendor_cfg_dir/allow_cmdline.conf";
    my $distr_allow_fedora = "$distrib_vendor_cfg_dir/allow_fedora.conf";
    my $allow_fedora = "$system_vendor_cfg_dir/allow_fedora.conf";
    my $test1 = "$system_vendor_cfg_dir/test1.conf";

    write_file($distr_allow_cmdline, $POLICY_TOML_ALLOW_CMDLINE);
    write_file($distr_allow_fedora, $POLICY_TOML_ALLOW_FEDORA);
    write_file($test1, $POLICY_TOML_TEST_1);
    write_file($allow_fedora, $POLICY_TOML_TEST_2);

    $base->setup();
    my $vcm = $base->get_vendor_change_manager();

    my $files = $vcm->get_policy_files();
    # SWIG custom typemap converts vector<path> to array of strings in Perl
    my @files = @$files;

    # allow_fedora overrides (masks) distr_allow_fedora -> only 3 files loaded
    is(scalar(@files), 3, "Got 3 policy files");
    is($files[0], $distr_allow_cmdline, "File 0 is distr_allow_cmdline");
    is($files[1], $allow_fedora, "File 1 is allow_fedora");
    is($files[2], $test1, "File 2 is test1");

    # Only configuration files in system_vendor_cfg_dir are manageable
    ok(!$vcm->is_policy_file_manageable($distr_allow_cmdline), "distr_allow_cmdline is not manageable");
    ok(!$vcm->is_policy_file_manageable($distr_allow_fedora), "distr_allow_fedora is not manageable");
    ok($vcm->is_policy_file_manageable($allow_fedora), "allow_fedora is manageable");
    ok($vcm->is_policy_file_manageable($test1), "test1 is manageable");

    # allow_fedora overrides (masks) distr_allow_fedora
    is($vcm->get_masked_policy_file($distr_allow_cmdline), "", "distr_allow_cmdline masks nothing");
    is($vcm->get_masked_policy_file($distr_allow_fedora), "", "distr_allow_fedora masks nothing");
    is($vcm->get_masked_policy_file($allow_fedora), $distr_allow_fedora, "allow_fedora masks distr_allow_fedora");
    is($vcm->get_masked_policy_file($test1), "", "test1 masks nothing");

    # Test find_policy_file
    is($vcm->find_policy_file("allow_cmdline"), $distr_allow_cmdline, "find_policy_file(allow_cmdline)");
    is($vcm->find_policy_file("allow_fedora"), $allow_fedora, "find_policy_file(allow_fedora)");
    is($vcm->find_policy_file("test1"), $test1, "find_policy_file(test1)");
    is($vcm->find_policy_file("non_exist"), "", "find_policy_file(non_exist) returns empty");

    # Test remove_policy_file
    throws_ok {
        $vcm->remove_policy_file($distr_allow_cmdline);
    } qr//, "remove_policy_file throws on distribution file";

    $vcm->remove_policy_file("allow_fedora");
    $vcm->remove_policy_file("test1");

    $files = $vcm->get_policy_files();
    @files = @$files;
    is(scalar(@files), 2, "After removal, got 2 policy files");
    is($files[0], $distr_allow_cmdline, "File 0 is distr_allow_cmdline");
    is($files[1], $distr_allow_fedora, "File 1 is distr_allow_fedora");

    # Test save_policy_from_compact
    $vcm->save_policy_from_compact($POLICY_COMPACT_TEST_2, "test:code", "allow_fedora");
    is(read_file($allow_fedora), $POLICY_TOML_TEST_2, "save_policy_from_compact wrote correct content");

    # fail - file already exists
    throws_ok {
        $vcm->save_policy_from_compact($POLICY_COMPACT_TEST_2, "test:code", "allow_fedora");
    } qr//, "save_policy_from_compact throws on existing file";

    # Test save_policy_from_toml with TOML content string
    $vcm->save_policy_from_toml($POLICY_TOML_TEST_1, "test:code", "test1");
    is(read_file($test1), $POLICY_TOML_TEST_1, "save_policy_from_toml(content) wrote correct content");

    # Test save_policy_from_toml with TOML file
    my $installroot = $base->get_config()->get_installroot_option()->get_value();
    make_path("$installroot/tmp");
    my $path = "$installroot/tmp/toml_test1.conf";
    write_file($path, $POLICY_TOML_TEST_1);

    $vcm->save_policy_from_toml($path, "from_toml_file");
    my $from_toml_file = "$system_vendor_cfg_dir/from_toml_file.conf";
    is(read_file($from_toml_file), $POLICY_TOML_TEST_1, "save_policy_from_toml(path) wrote correct content");

    $files = $vcm->get_policy_files();
    @files = @$files;
    is(scalar(@files), 4, "After saves, got 4 policy files");
    is($files[0], $distr_allow_cmdline, "File 0 is distr_allow_cmdline");
    is($files[1], $allow_fedora, "File 1 is allow_fedora");
    is($files[2], $from_toml_file, "File 2 is from_toml_file");
    is($files[3], $test1, "File 3 is test1");
}

done_testing();
