# Copyright Contributors to the DNF5 project.
# SPDX-License-Identifier: GPL-2.0-or-later

import os
import shutil
import sys
import tempfile
import unittest

import libdnf5.base

# Import test_config after setting up sys.path
sys.path.insert(0, os.environ.get("PROJECT_BINARY_DIR", ".") + "/test/python3")
import test_config  # noqa: E402


POLICY_COMPACT_ALLOW_CMDLINE = '@in:[cmdline_repo="1"]'

POLICY_TOML_ALLOW_CMDLINE = '''version = '1.2'

[[incoming_packages]]
filters = [
  { filter = 'cmdline_repo', value = "1" }
]
'''

POLICY_COMPACT_ALLOW_FEDORA = 'in:"Fedora Project"'

POLICY_TOML_ALLOW_FEDORA = '''version = '1.2'

[[incoming_vendors]]
vendor = "Fedora Project"
'''

POLICY_COMPACT_TEST_1 = 'in:ei*" test ",eq:^"MyVendor ",out:"OldVendor"'

POLICY_TOML_TEST_1 = '''version = '1.2'

[[incoming_vendors]]
vendor = " test "
comparator = 'ICONTAINS'
exclude = true

[[equivalent_vendors]]
vendor = "MyVendor "
comparator = 'STARTSWITH'

[[outgoing_vendors]]
vendor = "OldVendor"
'''

POLICY_COMPACT_TEST_2 = 'in:"My Vendor"@in:[source_name="mypackage",version>="2.0"]'

POLICY_TOML_TEST_2 = '''version = '1.2'

[[incoming_vendors]]
vendor = "My Vendor"

[[incoming_packages]]
filters = [
  { filter = 'source_name', value = "mypackage" },
  { filter = 'version', value = "2.0", comparator = 'GTE' }
]
'''


class TestVendorChangeManager(unittest.TestCase):
    """Test VendorChangeManager API"""

    def setUp(self):
        self.base = libdnf5.base.Base()
        self.temp_dir = tempfile.mkdtemp(prefix="libdnf5_python3_vendortest.")

        # Create installroot directory first
        installroot = os.path.join(self.temp_dir, "installroot")
        os.makedirs(installroot, exist_ok=True)

        config = self.base.get_config()
        config.installroot = installroot
        config.cachedir = os.path.join(self.temp_dir, "cache")

        # Get install prefix from test config (generated by CMake)
        # This matches CMAKE_INSTALL_PREFIX from the build
        install_prefix = test_config.CMAKE_INSTALL_PREFIX
        # Convert to relative path by removing leading /
        install_prefix = install_prefix.lstrip("/")

        installroot = config.installroot
        # Create necessary directories
        os.makedirs(os.path.join(installroot, "tmp"), exist_ok=True)
        self.distrib_vendor_cfg_dir = os.path.join(installroot, install_prefix, "share/dnf5/vendors.d")
        self.system_vendor_cfg_dir = os.path.join(installroot, "etc/dnf/vendors.d")
        os.makedirs(self.distrib_vendor_cfg_dir, exist_ok=True)
        os.makedirs(self.system_vendor_cfg_dir, exist_ok=True)

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_load_policy_from_compact(self):
        """Test loading vendor policy from compact format"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        vcm.load_policy_from_compact(POLICY_COMPACT_TEST_1, "text:test")

        self.assertEqual(vcm.get_loaded_policies_count(), 1)
        self.assertEqual(vcm.get_loaded_policy_source(0), "text:test")
        self.assertEqual(vcm.get_loaded_policy_as_compact(0), POLICY_COMPACT_TEST_1)
        self.assertEqual(vcm.get_loaded_policy_as_toml(0), POLICY_TOML_TEST_1)

    def test_load_policy_from_toml_content(self):
        """Test loading vendor policy from TOML content string"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        vcm.load_policy_from_toml(POLICY_TOML_TEST_1, "text:test")

        self.assertEqual(vcm.get_loaded_policies_count(), 1)
        self.assertEqual(vcm.get_loaded_policy_source(0), "text:test")
        self.assertEqual(vcm.get_loaded_policy_as_compact(0), POLICY_COMPACT_TEST_1)
        self.assertEqual(vcm.get_loaded_policy_as_toml(0), POLICY_TOML_TEST_1)

    def test_load_policy_from_toml_file(self):
        """Test loading vendor policy from TOML file"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        installroot = self.base.get_config().installroot
        path = os.path.join(installroot, "tmp", "vendor_policy.conf")

        with open(path, 'w') as f:
            f.write(POLICY_TOML_TEST_1)

        vcm.load_policy_from_toml(path)

        self.assertEqual(vcm.get_loaded_policies_count(), 1)
        source = vcm.get_loaded_policy_source(0)
        self.assertEqual(source, "file://" + path)
        self.assertEqual(vcm.get_loaded_policy_as_compact(0), POLICY_COMPACT_TEST_1)
        self.assertEqual(vcm.get_loaded_policy_as_toml(0), POLICY_TOML_TEST_1)

    def test_convert_toml_to_compact(self):
        """Test converting TOML to compact format"""
        compact = libdnf5.base.VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_ALLOW_CMDLINE, "text:test")
        self.assertEqual(compact, POLICY_COMPACT_ALLOW_CMDLINE)

        compact = libdnf5.base.VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_ALLOW_FEDORA, "text:test")
        self.assertEqual(compact, POLICY_COMPACT_ALLOW_FEDORA)

        compact = libdnf5.base.VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_TEST_1, "text:test")
        self.assertEqual(compact, POLICY_COMPACT_TEST_1)

        compact = libdnf5.base.VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_TEST_2, "text:test")
        self.assertEqual(compact, POLICY_COMPACT_TEST_2)

    def test_convert_toml_file_to_compact(self):
        """Test converting TOML file to compact format"""
        installroot = self.base.get_config().installroot
        path = os.path.join(installroot, "tmp", "vendor_policy.conf")

        with open(path, 'w') as f:
            f.write(POLICY_TOML_TEST_1)

        compact = libdnf5.base.VendorChangeManager.convert_policy_toml_to_compact(path)
        self.assertEqual(compact, POLICY_COMPACT_TEST_1)

    def test_convert_compact_to_toml(self):
        """Test converting compact format to TOML"""
        toml = libdnf5.base.VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_ALLOW_CMDLINE, "text:test")
        self.assertEqual(toml, POLICY_TOML_ALLOW_CMDLINE)

        toml = libdnf5.base.VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_ALLOW_FEDORA, "text:test")
        self.assertEqual(toml, POLICY_TOML_ALLOW_FEDORA)

        toml = libdnf5.base.VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_TEST_1, "text:test")
        self.assertEqual(toml, POLICY_TOML_TEST_1)

        toml = libdnf5.base.VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_TEST_2, "text:test")
        self.assertEqual(toml, POLICY_TOML_TEST_2)

    def test_unload_policies(self):
        """Test unload all vendor change policies from memory"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        vcm.load_policy_from_compact('eq:"V1", in:"V2"', "text:test1")
        vcm.load_policy_from_compact('out:"V5", eq:"V4"', "text:test2")
        self.assertEqual(vcm.get_loaded_policies_count(), 2)

        unloaded_count = vcm.unload_policies()
        self.assertEqual(unloaded_count, 2)
        self.assertEqual(vcm.get_loaded_policies_count(), 0)

    def test_unload_policy(self):
        """Test unload a vendor change policy at the specified index"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        vcm.load_policy_from_compact('in:"V0"', "text:source0")
        vcm.load_policy_from_compact('in:"V1"', "text:source1")
        vcm.load_policy_from_compact('in:"V2"', "text:source2")
        vcm.load_policy_from_compact('in:"V3"', "text:source3")
        vcm.load_policy_from_compact('in:"V4"', "text:source4")
        vcm.load_policy_from_compact('in:"V5"', "text:source5")
        self.assertEqual(vcm.get_loaded_policies_count(), 6)

        vcm.unload_policy(2)
        self.assertEqual(vcm.get_loaded_policies_count(), 5)
        self.assertEqual(vcm.get_loaded_policy_source(2), "text:source3")

        vcm.unload_policy(4)
        self.assertEqual(vcm.get_loaded_policies_count(), 4)
        self.assertEqual(vcm.get_loaded_policy_source(3), "text:source4")

        vcm.unload_policy(0)
        self.assertEqual(vcm.get_loaded_policies_count(), 3)
        self.assertEqual(vcm.get_loaded_policy_source(0), "text:source1")
        self.assertEqual(vcm.get_loaded_policy_source(2), "text:source4")

        with self.assertRaises(libdnf5.exception.BaseVendorChangeManagerError):
            vcm.unload_policy(999)

    def test_unload_policies_matching_source(self):
        """Test unload vendor change policies whose source matches the specified pattern"""
        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        vcm.load_policy_from_compact('in:"V1"', "text:source1")
        vcm.load_policy_from_compact('in:"V2"', "text:source2")
        vcm.load_policy_from_compact('in:"NV2"', "text:new_source2")
        vcm.load_policy_from_compact('in:"V3"', "text:source3")
        vcm.load_policy_from_compact('in:"V4"', "text:source4")
        vcm.load_policy_from_compact('in:"NV3"', "text:source3")
        self.assertEqual(vcm.get_loaded_policies_count(), 6)

        unloaded_count = vcm.unload_policies_matching_source("text:source3")
        self.assertEqual(unloaded_count, 2)
        self.assertEqual(vcm.get_loaded_policies_count(), 4)

        unloaded_count = vcm.unload_policies_matching_source("te?t:*source2")
        self.assertEqual(unloaded_count, 2)
        self.assertEqual(vcm.get_loaded_policies_count(), 2)

    def test_extract_policy_base_filename(self):
        """Test extracting base filename from policy file path"""
        full_path = "/etc/dnf/vendors.d/my-policy.conf"
        base_name = libdnf5.base.VendorChangeManager.extract_policy_base_filename(full_path)
        self.assertEqual(base_name, "my-policy")

    def test_work_with_files(self):
        """Test comprehensive file operations"""
        # Create TOML files
        distr_allow_cmdline = os.path.join(self.distrib_vendor_cfg_dir, "allow_cmdline.conf")
        distr_allow_fedora = os.path.join(self.distrib_vendor_cfg_dir, "allow_fedora.conf")
        allow_fedora = os.path.join(self.system_vendor_cfg_dir, "allow_fedora.conf")
        test1 = os.path.join(self.system_vendor_cfg_dir, "test1.conf")

        with open(distr_allow_cmdline, 'w') as f:
            f.write(POLICY_TOML_ALLOW_CMDLINE)
        with open(distr_allow_fedora, 'w') as f:
            f.write(POLICY_TOML_ALLOW_FEDORA)
        with open(test1, 'w') as f:
            f.write(POLICY_TOML_TEST_1)
        with open(allow_fedora, 'w') as f:
            f.write(POLICY_TOML_TEST_2)

        self.base.setup()
        vcm = self.base.get_vendor_change_manager()

        files = vcm.get_policy_files()

        # allow_fedora overrides (masks) distr_allow_fedora -> only 3 files loaded
        self.assertEqual(len(files), 3)
        self.assertEqual(files[0], distr_allow_cmdline)
        self.assertEqual(files[1], allow_fedora)
        self.assertEqual(files[2], test1)

        # Only configuration files in system_vendor_cfg_dir are manageable
        self.assertFalse(vcm.is_policy_file_manageable(distr_allow_cmdline))
        self.assertFalse(vcm.is_policy_file_manageable(distr_allow_fedora))
        self.assertTrue(vcm.is_policy_file_manageable(allow_fedora))
        self.assertTrue(vcm.is_policy_file_manageable(test1))

        # allow_fedora overrides (masks) distr_allow_fedora
        self.assertEqual(vcm.get_masked_policy_file(distr_allow_cmdline), "")
        self.assertEqual(vcm.get_masked_policy_file(distr_allow_fedora), "")
        self.assertEqual(vcm.get_masked_policy_file(allow_fedora), distr_allow_fedora)
        self.assertEqual(vcm.get_masked_policy_file(test1), "")

        # Test find_policy_file
        self.assertEqual(vcm.find_policy_file("allow_cmdline"), distr_allow_cmdline)
        self.assertEqual(vcm.find_policy_file("allow_fedora"), allow_fedora)
        self.assertEqual(vcm.find_policy_file("test1"), test1)
        self.assertEqual(vcm.find_policy_file("non_exist"), "")

        # Test remove_policy_file
        with self.assertRaises(libdnf5.exception.BaseVendorChangeManagerError):
            vcm.remove_policy_file(distr_allow_cmdline)
        vcm.remove_policy_file("allow_fedora")
        vcm.remove_policy_file("test1")

        files = vcm.get_policy_files()
        self.assertEqual(len(files), 2)
        self.assertEqual(files[0], distr_allow_cmdline)
        self.assertEqual(files[1], distr_allow_fedora)

        # Test save_policy_from_compact
        vcm.save_policy_from_compact(POLICY_COMPACT_TEST_2, "test:code", "allow_fedora")
        with open(allow_fedora, 'r') as f:
            self.assertEqual(f.read(), POLICY_TOML_TEST_2)

        # fail - file already exists
        with self.assertRaises(libdnf5.exception.BaseVendorChangeManagerError):
            vcm.save_policy_from_compact(POLICY_COMPACT_TEST_2, "test:code", "allow_fedora")

        # Test save_policy_from_toml with TOML content string
        vcm.save_policy_from_toml(POLICY_TOML_TEST_1, "test:code", "test1")
        with open(test1, 'r') as f:
            self.assertEqual(f.read(), POLICY_TOML_TEST_1)

        # Test save_policy_from_toml with TOML file
        installroot = self.base.get_config().installroot
        path = os.path.join(installroot, "tmp", "toml_test1.conf")
        with open(path, 'w') as f:
            f.write(POLICY_TOML_TEST_1)

        vcm.save_policy_from_toml(path, "from_toml_file")
        from_toml_file = os.path.join(self.system_vendor_cfg_dir, "from_toml_file.conf")
        with open(from_toml_file, 'r') as f:
            self.assertEqual(f.read(), POLICY_TOML_TEST_1)

        files = vcm.get_policy_files()
        self.assertEqual(len(files), 4)
        self.assertEqual(files[0], distr_allow_cmdline)
        self.assertEqual(files[1], allow_fedora)
        self.assertEqual(files[2], from_toml_file)
        self.assertEqual(files[3], test1)


if __name__ == '__main__':
    unittest.main()
