# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    buildvm-14.phx2.fedoraproject.org
#BUILDTIME:    Mon Jul 23 12:00:58 2018
#SOURCERPM:    CQRlib-1.1.2-16.fc29.src.rpm

#RPMVERSION:   4.14.2-rc1

#INSTALLTIME:  Thu Jan 10 11:28:11 2019

#OS:           linux
#SIZE:           111606
#ARCHIVESIZE:           113100
#ARCH:         x86_64
BuildArch:     x86_64
Name:          CQRlib
Version:       1.1.2
Release:       16.fc29
License:       LGPLv2+
Group:         System Environment/Libraries
Summary:       ANSI C API for quaternion arithmetic and rotation
Distribution:  Fedora Project

URL:           http://cqrlib.sourceforge.net/
Vendor:        Fedora Project
Packager:      Fedora Project





Provides:      CQRlib = 1.1.2-16.fc29
Provides:      CQRlib(x86-64) = 1.1.2-16.fc29
Provides:      libCQRlib.so.2()(64bit)
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
CQRlib is an ANSI C implementation of a utility library for quaternion
arithmetic and quaternion rotation math.
%files
%changelog
