# Copyright Contributors to the DNF5 project.
# SPDX-License-Identifier: GPL-2.0-or-later

require 'test/unit'
include Test::Unit::Assertions

require 'libdnf5/base'
require 'tmpdir'
require 'fileutils'

# Try to load test config generated by CMake (optional)
begin
    if ENV['PROJECT_BINARY_DIR']
        $LOAD_PATH.unshift(ENV['PROJECT_BINARY_DIR'] + '/test/ruby')
        require 'test_config'
    end
rescue LoadError
    # TestConfig not available, will use fallback
end

POLICY_COMPACT_ALLOW_CMDLINE = '@in:[cmdline_repo="1"]'

POLICY_TOML_ALLOW_CMDLINE = <<~EOF
version = '1.2'

[[incoming_packages]]
filters = [
  { filter = 'cmdline_repo', value = "1" }
]
EOF

POLICY_COMPACT_ALLOW_FEDORA = 'in:"Fedora Project"'

POLICY_TOML_ALLOW_FEDORA = <<~EOF
version = '1.2'

[[incoming_vendors]]
vendor = "Fedora Project"
EOF

POLICY_COMPACT_TEST_1 = 'in:ei*" test ",eq:^"MyVendor ",out:"OldVendor"'

POLICY_TOML_TEST_1 = <<~EOF
version = '1.2'

[[incoming_vendors]]
vendor = " test "
comparator = 'ICONTAINS'
exclude = true

[[equivalent_vendors]]
vendor = "MyVendor "
comparator = 'STARTSWITH'

[[outgoing_vendors]]
vendor = "OldVendor"
EOF

POLICY_COMPACT_TEST_2 = 'in:"My Vendor"@in:[source_name="mypackage",version>="2.0"]'

POLICY_TOML_TEST_2 = <<~EOF
version = '1.2'

[[incoming_vendors]]
vendor = "My Vendor"

[[incoming_packages]]
filters = [
  { filter = 'source_name', value = "mypackage" },
  { filter = 'version', value = "2.0", comparator = 'GTE' }
]
EOF


class TestVendorChangeManager < Test::Unit::TestCase
    def setup
        @base = Libdnf5::Base::Base.new()
        @temp_dir = Dir.mktmpdir("libdnf5_ruby_vendortest.")

        config = @base.get_config()
        config.get_installroot_option().set(File.join(@temp_dir, "installroot"))
        config.get_cachedir_option().set(File.join(@temp_dir, "cache"))

        # Get install prefix from test config (generated by CMake), fallback to /usr
        install_prefix = (TestConfig::CMAKE_INSTALL_PREFIX rescue "/usr")
        # Convert to relative path by removing leading /
        install_prefix = install_prefix.sub(/^\//, '')  # Remove leading slash

        installroot = config.get_installroot_option().get_value()

        # Create necessary directories
        FileUtils.mkdir_p(File.join(installroot, "tmp"))
        @distrib_vendor_cfg_dir = File.join(installroot, install_prefix, "share/dnf5/vendors.d")
        @system_vendor_cfg_dir = File.join(installroot, "etc/dnf/vendors.d")
        FileUtils.mkdir_p(@distrib_vendor_cfg_dir)
        FileUtils.mkdir_p(@system_vendor_cfg_dir)
    end

    def teardown
        FileUtils.rm_rf(@temp_dir)
    end

    def test_load_policy_from_compact
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        vcm.load_policy_from_compact(POLICY_COMPACT_TEST_1, "text:test")

        assert_equal(1, vcm.get_loaded_policies_count())
        assert_equal("text:test", vcm.get_loaded_policy_source(0))
        assert_equal(POLICY_COMPACT_TEST_1, vcm.get_loaded_policy_as_compact(0))
        assert_equal(POLICY_TOML_TEST_1, vcm.get_loaded_policy_as_toml(0))
    end

    def test_load_policy_from_toml_content
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        vcm.load_policy_from_toml(POLICY_TOML_TEST_1, "text:test")

        assert_equal(1, vcm.get_loaded_policies_count())
        assert_equal("text:test", vcm.get_loaded_policy_source(0))
        assert_equal(POLICY_COMPACT_TEST_1, vcm.get_loaded_policy_as_compact(0))
        assert_equal(POLICY_TOML_TEST_1, vcm.get_loaded_policy_as_toml(0))
    end

    def test_load_policy_from_toml_file
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        installroot = @base.get_config().get_installroot_option().get_value()
        path = File.join(installroot, "tmp", "vendor_policy.conf")

        File.write(path, POLICY_TOML_TEST_1)

        vcm.load_policy_from_toml(path)

        assert_equal(1, vcm.get_loaded_policies_count())
        source = vcm.get_loaded_policy_source(0)
        assert_equal("file://" + path, source)
        assert_equal(POLICY_COMPACT_TEST_1, vcm.get_loaded_policy_as_compact(0))
        assert_equal(POLICY_TOML_TEST_1, vcm.get_loaded_policy_as_toml(0))
    end

    def test_convert_toml_to_compact
        compact = Libdnf5::Base::VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_ALLOW_CMDLINE, "text:test")
        assert_equal(POLICY_COMPACT_ALLOW_CMDLINE, compact)

        compact = Libdnf5::Base::VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_ALLOW_FEDORA, "text:test")
        assert_equal(POLICY_COMPACT_ALLOW_FEDORA, compact)

        compact = Libdnf5::Base::VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_TEST_1, "text:test")
        assert_equal(POLICY_COMPACT_TEST_1, compact)

        compact = Libdnf5::Base::VendorChangeManager.convert_policy_toml_to_compact(
            POLICY_TOML_TEST_2, "text:test")
        assert_equal(POLICY_COMPACT_TEST_2, compact)
    end

    def test_convert_toml_file_to_compact
        installroot = @base.get_config().get_installroot_option().get_value()
        path = File.join(installroot, "tmp", "vendor_policy.conf")

        File.write(path, POLICY_TOML_TEST_1)

        compact = Libdnf5::Base::VendorChangeManager.convert_policy_toml_to_compact(path)
        assert_equal(POLICY_COMPACT_TEST_1, compact)
    end

    def test_convert_compact_to_toml
        toml = Libdnf5::Base::VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_ALLOW_CMDLINE, "text:test")
        assert_equal(POLICY_TOML_ALLOW_CMDLINE, toml)

        toml = Libdnf5::Base::VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_ALLOW_FEDORA, "text:test")
        assert_equal(POLICY_TOML_ALLOW_FEDORA, toml)

        toml = Libdnf5::Base::VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_TEST_1, "text:test")
        assert_equal(POLICY_TOML_TEST_1, toml)

        toml = Libdnf5::Base::VendorChangeManager.convert_policy_compact_to_toml(
            POLICY_COMPACT_TEST_2, "text:test")
        assert_equal(POLICY_TOML_TEST_2, toml)
    end

    def test_unload_policies
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        vcm.load_policy_from_compact('eq:"V1", in:"V2"', "text:test1")
        vcm.load_policy_from_compact('out:"V5", eq:"V4"', "text:test2")
        assert_equal(2, vcm.get_loaded_policies_count())

        unloaded_count = vcm.unload_policies()
        assert_equal(2, unloaded_count)
        assert_equal(0, vcm.get_loaded_policies_count())
    end

    def test_unload_policy
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        vcm.load_policy_from_compact('in:"V0"', "text:source0")
        vcm.load_policy_from_compact('in:"V1"', "text:source1")
        vcm.load_policy_from_compact('in:"V2"', "text:source2")
        vcm.load_policy_from_compact('in:"V3"', "text:source3")
        vcm.load_policy_from_compact('in:"V4"', "text:source4")
        vcm.load_policy_from_compact('in:"V5"', "text:source5")
        assert_equal(6, vcm.get_loaded_policies_count())

        vcm.unload_policy(2)
        assert_equal(5, vcm.get_loaded_policies_count())
        assert_equal("text:source3", vcm.get_loaded_policy_source(2))

        vcm.unload_policy(4)
        assert_equal(4, vcm.get_loaded_policies_count())
        assert_equal("text:source4", vcm.get_loaded_policy_source(3))

        vcm.unload_policy(0)
        assert_equal(3, vcm.get_loaded_policies_count())
        assert_equal("text:source1", vcm.get_loaded_policy_source(0))
        assert_equal("text:source4", vcm.get_loaded_policy_source(2))

        assert_raise(Libdnf5::Exception::BaseVendorChangeManagerError) do
            vcm.unload_policy(999)
        end
    end

    def test_unload_policies_matching_source
        @base.setup()
        vcm = @base.get_vendor_change_manager()

        vcm.load_policy_from_compact('in:"V1"', "text:source1")
        vcm.load_policy_from_compact('in:"V2"', "text:source2")
        vcm.load_policy_from_compact('in:"NV2"', "text:new_source2")
        vcm.load_policy_from_compact('in:"V3"', "text:source3")
        vcm.load_policy_from_compact('in:"V4"', "text:source4")
        vcm.load_policy_from_compact('in:"NV3"', "text:source3")
        assert_equal(6, vcm.get_loaded_policies_count())

        unloaded_count = vcm.unload_policies_matching_source("text:source3")
        assert_equal(2, unloaded_count)
        assert_equal(4, vcm.get_loaded_policies_count())

        unloaded_count = vcm.unload_policies_matching_source("te?t:*source2")
        assert_equal(2, unloaded_count)
        assert_equal(2, vcm.get_loaded_policies_count())
    end

    def test_extract_policy_base_filename
        full_path = "/etc/dnf/vendors.d/my-policy.conf"
        base_name = Libdnf5::Base::VendorChangeManager.extract_policy_base_filename(full_path)
        assert_equal("my-policy", base_name)
    end

    def test_work_with_files
        # Create TOML files
        distr_allow_cmdline = File.join(@distrib_vendor_cfg_dir, "allow_cmdline.conf")
        distr_allow_fedora = File.join(@distrib_vendor_cfg_dir, "allow_fedora.conf")
        allow_fedora = File.join(@system_vendor_cfg_dir, "allow_fedora.conf")
        test1 = File.join(@system_vendor_cfg_dir, "test1.conf")

        File.write(distr_allow_cmdline, POLICY_TOML_ALLOW_CMDLINE)
        File.write(distr_allow_fedora, POLICY_TOML_ALLOW_FEDORA)
        File.write(test1, POLICY_TOML_TEST_1)
        File.write(allow_fedora, POLICY_TOML_TEST_2)

        @base.setup()
        vcm = @base.get_vendor_change_manager()

        files = vcm.get_policy_files()

        # allow_fedora overrides (masks) distr_allow_fedora -> only 3 files loaded
        assert_equal(3, files.size())
        assert_equal(distr_allow_cmdline, files[0])
        assert_equal(allow_fedora, files[1])
        assert_equal(test1, files[2])

        # Only configuration files in system_vendor_cfg_dir are manageable
        assert_equal(false, vcm.is_policy_file_manageable(distr_allow_cmdline))
        assert_equal(false, vcm.is_policy_file_manageable(distr_allow_fedora))
        assert_equal(true, vcm.is_policy_file_manageable(allow_fedora))
        assert_equal(true, vcm.is_policy_file_manageable(test1))

        # allow_fedora overrides (masks) distr_allow_fedora
        assert_equal("", vcm.get_masked_policy_file(distr_allow_cmdline))
        assert_equal("", vcm.get_masked_policy_file(distr_allow_fedora))
        assert_equal(distr_allow_fedora, vcm.get_masked_policy_file(allow_fedora))
        assert_equal("", vcm.get_masked_policy_file(test1))

        # Test find_policy_file
        assert_equal(distr_allow_cmdline, vcm.find_policy_file("allow_cmdline"))
        assert_equal(allow_fedora, vcm.find_policy_file("allow_fedora"))
        assert_equal(test1, vcm.find_policy_file("test1"))
        assert_equal("", vcm.find_policy_file("non_exist"))

        # Test remove_policy_file
        assert_raise(Libdnf5::Exception::BaseVendorChangeManagerError) do
            vcm.remove_policy_file(distr_allow_cmdline)
        end
        vcm.remove_policy_file("allow_fedora")
        vcm.remove_policy_file("test1")

        files = vcm.get_policy_files()
        assert_equal(2, files.size())
        assert_equal(distr_allow_cmdline, files[0])
        assert_equal(distr_allow_fedora, files[1])

        # Test save_policy_from_compact
        vcm.save_policy_from_compact(POLICY_COMPACT_TEST_2, "test:code", "allow_fedora")
        assert_equal(POLICY_TOML_TEST_2, File.read(allow_fedora))

        # fail - file already exists
        assert_raise do
            vcm.save_policy_from_compact(POLICY_COMPACT_TEST_2, "test:code", "allow_fedora")
        end

        # Test save_policy_from_toml with TOML content string
        vcm.save_policy_from_toml(POLICY_TOML_TEST_1, "test:code", "test1")
        assert_equal(POLICY_TOML_TEST_1, File.read(test1))

        # Test save_policy_from_toml with TOML file
        installroot = @base.get_config().get_installroot_option().get_value()
        path = File.join(installroot, "tmp", "toml_test1.conf")
        File.write(path, POLICY_TOML_TEST_1)

        vcm.save_policy_from_toml(path, "from_toml_file")
        from_toml_file = File.join(@system_vendor_cfg_dir, "from_toml_file.conf")
        assert_equal(POLICY_TOML_TEST_1, File.read(from_toml_file))

        files = vcm.get_policy_files()
        assert_equal(4, files.size())
        assert_equal(distr_allow_cmdline, files[0])
        assert_equal(allow_fedora, files[1])
        assert_equal(from_toml_file, files[2])
        assert_equal(test1, files[3])
    end
end
