---
name: Pre Commit
on:
  pull_request:


jobs:
  pre-commit:
    name: Pre Commit Hooks
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y python3-rpm
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
