name: Test Packit
on:
  pull_request:

jobs:
  test-packit:
    name: Test if Packit is done
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install wait-for-copr
        run: pip install git+https://github.com/packit/wait-for-copr

      - name: wait for copr
        env:
          # env variables for readability
          REPO: ${{ github.repository_owner }}
          PROJ: ${{ github.event.repository.name }}
          PR: ${{ github.event.number }}
          HASH: ${{ github.sha }}
        run: |
          wait-for-copr --owner packit --project $REPO-$PROJ-$PR $PROJ ${HASH:0:7}

      - name: print success
        run: echo "success"
